let handler = async (m, { conn, command, text }) => {
		if (!text) throw 'Input Name'
		let txt = `${command}`
		if (txt === "simp") {
		let simpp = `Buruan, panggil gue SIMP, ato BAPERAN. ini MURNI PERASAAN GUE. Gue pengen genjot bareng *${text.capitalize()}*. Ini seriusan, suaranya yang imut, mukanya yang cantik, apalagi badannya yang aduhai ningkatin gairah gue buat genjot *${text.capitalize()}*. Setiap lapisan kulitnya pengen gue jilat. Saat gue mau crot, gue bakal moncrot sepenuh hati, bisa di perut, muka, badan, teteknya, sampai lubang burit pun bakal gue crot sampai puncak klimaks. Gue bakal meluk dia abis gue moncrot, lalu nanya gimana kabarnya, ngrasain enggas bareng saat telanjang. Dia bakal bilang kalau genjotan gue mantep dan nyatain perasaannya ke gue, bilang kalo dia cinta ama gue. Gue bakal bilang balik seberapa gue cinta ama dia, dan dia bakal kecup gue di pipi. Terus kita ganti pakaian dan ngabisin waktu nonton film, sambil pelukan ama makan hidangan favorit. Gue mau *${text.capitalize()}* jadi pacar, pasangan, istri, dan idup gue. Gue cinta dia dan ingin dia jadi bagian tubuh gue. Lo kira ini copypaste? Kagak cok. Gue ngetik tiap kata nyatain prasaan gue. Setiap kali elo nanya dia siapa, denger ini baik-baik : DIA ISTRI GUE. Gue sayang *${text.toUpperCase()}*, dan INI MURNI PIKIRAN DAN PERASAAN GUE.`
		await conn.sendMessage(m.chat, { image: { url: "https://telegra.ph//file/a0f0f6e497c99a5018fba.jpg"}, caption: simpp, quoted: m } )
		} else if (txt === "wangy") {
		let wangyy =  `*${text.toUpperCase()} ${text.toUpperCase()} ${text.toUpperCase()}* ❤️ ❤️ ❤️ WANGI WANGI WANGI WANGI HU HA HU HA HU HA, aaaah baunya rambut *${text.capitalize()}* wangi aku mau nyiumin aroma wanginya *${text.capitalize()}* AAAAAAAAH ~ Rambutnya.... aaah rambutnya juga pengen aku elus-elus ~~ AAAAAH *${text.capitalize()}* keluar pertama kali di anime juga manis ❤️ ❤️ ❤️ banget AAAAAAAAH *${text.toUpperCase()}* AAAAA LUCCUUUUUUUUUUUUUUU............ *${text.toUpperCase()}* AAAAAAAAAAAAAAAAAAAAGH ❤️ ❤️ ❤ ️apa ? *${text.capitalize()}* itu gak nyata ? Cuma HALU katamu ? nggak, ngak ngak ngak ngak NGAAAAAAAAK GUA GAK PERCAYA ITU DIA NYATA NGAAAAAAAAAAAAAAAAAK PEDULI BANGSAAAAAT !! GUA GAK PEDULI SAMA KENYATAAN POKOKNYA GAK PEDULI. ❤️ ❤️ ❤️ *${text.capitalize()}* ... *${text.capitalize()}* di laptop ngeliatin gw, *${text.capitalize()}* .. kamu percaya sama aku ? aaaaaaaaaaah syukur *${text.capitalize()}* aku gak mau merelakan *${text.capitalize()}* aaaaaah ❤️ ❤️ ❤️ YEAAAAAAAAAAAH GUA MASIH PUNYA *${text.toUpperCase()}* SENDIRI PUN NGGAK SAMA AAAAAAAAAAAAAAH`
		await conn.sendMessage(m.chat, { image: { url: "https://telegra.ph//file/a0f0f6e497c99a5018fba.jpg"}, caption: wangyy, quoted: m } )
		} else if (txt === "nenen") {
		let nenenn = `NENEN NENEN KEPENGEN NENEN SAMA *${text.toUpperCase()}*. TETEK GEDE NAN KENCANG MILIK *${text.toUpperCase()}* MEMBUATKU KEPENGEN NENEN. DIBALUT PAKAIAN KETAT YANG ADUHAI CROOOOTOTOTOTOTOT ANJING SANGE GUA BANGSAT. *${text.toUpperCase()}*, PLIS DENGERIN BAIK BAIK. TOLONG BUKA BAJU SEBENTAR SAJA PLISSS TOLOOONG BANGET, BIARKAN MULUT KERINGKU BISA MENGECAP NENEN *${text.toUpperCase()}*. BIARKAN AKU MENGENYOT NENENMU ${text.toUpperCase()}. AKU RELA NGASIH SESEMBAHAN APA AJA BERAPAPUN ITU DUIT YANG AKU BAKAR KHUSUS TERKHUSUS BUATMU. TAPI TOLOOOONG BANGET BUKA BAJUMU AKU MAU NENEN. NENEN NENEEEEN NENEN *${text.toUpperCase()}* WANGIIII`
		await conn.sendMessage(m.chat, { image: { url: "https://telegra.ph//file/a0f0f6e497c99a5018fba.jpg"}, caption: nenenn, quoted: m } )
		} else if (txt === "sherk") {
		let sherkk = `Usiaku 22 tahun. Aku sangat mencintai *${text.capitalize()}*, aku punya semua Figurine dan wallpapernya. Aku berdoa setiap malam dan berterima kasih atas segala hal yang telah ia berikan kepadaku. " *${text.capitalize()}* adalah cinta " aku bilang " *${text.capitalize()}* adalah Tujuan Hidupku ". Temanku datang ke kamarku dan berkata "HALU LU ANJING !!". Aku tau dia cemburu atas kesetiaanku kepada *${text.capitalize()}*. Lalu kukatakan padanya "BACOT NJING !!". Temanku menampol kepalaku dan menyuruhku untuk tidur. Kepalaku sakit dan aku menangis. Aku rebahan di kasur yang dingin, lalu ada sesuatu yang hangat menyentuhku. Ternyata *${text.capitalize()}* datang ke dalam kamarku, Aku begitu senang bertemu *${text.capitalize()}*. Dia membisikan ke telingaku, "Kamu adalah impianku" Dengan tangannya dia meraih diriku. Aku melebarkan pantatku keatas demi *${text.capitalize()}*. Dia menusukan sesuatu kedalam Anggusku. begitu sakit, tapi kulakukan itu demi *${text.capitalize()}*. Aku ingin memberikan kepuasan kepada *${text.capitalize()}*. Dia meraum bagaikan singa, disaat dia melepaskan cintanya kedalam Anggusku. Temanku masuk kekamarku dan berkata "....... Anjing". *${text.capitalize()}* melihat temanku dan berkata " Semua sudah berakhir" Dengan menggunakan kemampuannya Stellar Restoration *${text.capitalize()}* pergi meninggalkan kamarku. " *${text.capitalize()}* itu cinta " " *${text.capitalize()}* itu kehidupan ".`
		await conn.sendMessage(m.chat, { image: { url: "https://telegra.ph//file/a0f0f6e497c99a5018fba.jpg"}, caption: sherkk, quoted: m } )
		}
	}
handler.help = [ 'Simp', 'Nenen', 'Wangy', 'Sherk' ]
handler.tags = [ 'misc' ]
handler.command = /^(simp|nenen|wangy|sherk)$/i

export default handler